name: Publish

on:
  pull_request:
    branches: [ "publish" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  dockerize:
    name: Dockerize
    needs: build
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ variables.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
      - name: Build Docker image
        run: docker build -t $USERNAME/inno-eco -f .\INNOEcoSystem.Api\Dockerfile .
      - name: Login to Docker account
        run: docker login -u $USERNAME -p $PASSWORD #--password-stdin
      - name: Push Docker image
        run: docker push $USERNAME/inno-eco
